# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for generating FoldRun Viewer summary.json and diagnostic plots for AlphaFold 3."""

from __future__ import annotations

import io
import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)

AF3_GEMINI_MODELS = ("gemini-3.1-pro-preview", "gemini-2.5-pro", "gemini-2.5-flash")
AF3_AI_DISCLAIMER = (
    "\n\n---\n"
    "*This analysis was generated by AI (Google Gemini) and has not been "
    "peer-reviewed. It is intended as a starting point for interpretation, "
    "not as expert biological advice. Predictions should be validated "
    "experimentally by qualified scientists before use in research or "
    "clinical decisions.*"
)


def build_af3_expert_prompt(summary_data: dict[str, Any]) -> str:
    """Build the 8-section AlphaFold 3 structural biology prompt from summary.json."""
    best = summary_data.get("best_prediction") or {}
    summary = summary_data.get("summary") or {}
    pinfo = summary.get("protein_info") or {}
    qmetrics = summary.get("quality_metrics") or {}
    jmeta = pinfo.get("job_metadata") or {}

    job_id = summary_data.get("job_id") or "unknown"
    query_name = summary_data.get("query_name") or job_id
    total_len = (
        pinfo.get("total_length")
        or pinfo.get("sequence_length")
        or len(best.get("plddt_scores") or [])
    )
    num_chains = pinfo.get("num_chains") or len(pinfo.get("chain_composition") or []) or 1
    sample_name = best.get("sample_name") or qmetrics.get("best_model") or "seed_1_sample_0"
    duration_fmt = jmeta.get("duration_formatted") or "N/A"
    accel = jmeta.get("accelerator_type") or jmeta.get("gpu_type") or "NVIDIA_H100_80GB"

    input_query = pinfo.get("input_query_json") or {}
    has_unpaired_msa = False
    seq_entries = input_query.get("sequences") or []
    seq_lines = []
    for ent in seq_entries:
        for mol_t in ("protein", "rna", "dna"):
            if mol_t in ent:
                c = ent[mol_t]
                cid = c.get("id", "A")
                s = c.get("sequence", "")
                if "unpairedMsa" in c and c.get("unpairedMsa") == "":
                    has_unpaired_msa = True
                seq_lines.append(f">{query_name}|Chain_{cid}|{mol_t}\n{s}")
        for lig_t in ("ligand", "ion"):
            if lig_t in ent:
                c = ent[lig_t]
                cid = c.get("id", "L")
                ccd = c.get("ccdCodes") or c.get("ion") or c.get("smiles")
                seq_lines.append(f"# Chain {cid} ({lig_t}): {ccd}")

    is_msa_free = (
        "msa-free" in sample_name.lower() or "msa_free" in sample_name.lower() or has_unpaired_msa
    )
    mode_desc = (
        "Zero-MSA (--msa-free, rapid single-sequence screening)"
        if is_msa_free
        else "Full 630 GB MSA + PDB Templates (Jackhmmer/Hmmsearch over UniRef90, MGnify, BFD-small, UniProt, PDB mmCIF templates, RNACentral, Rfam on local NVMe SSD)"
    )

    chain_desc_lines = []
    for ci in pinfo.get("chain_composition") or []:
        cid = ci.get("chain_id", "A")
        mtype = ci.get("molecule_type", "protein")
        if mtype in ("ligand", "ion"):
            comps = ci.get("ccd_codes") or ci.get("comp_ids") or ci.get("smiles") or mtype
            chain_desc_lines.append(f"- Chain {cid}: {mtype} ({comps})")
        else:
            rcount = ci.get("residue_count", "N/A")
            chain_desc_lines.append(f"- Chain {cid}: {mtype}, {rcount} residues/nt")
    chain_desc = (
        "\n".join(chain_desc_lines)
        if chain_desc_lines
        else f"- {num_chains} chain(s), {total_len} total tokens/residues"
    )

    ranking_score = float(best.get("ranking_score") or qmetrics.get("best_ranking_score") or 0.0)
    ptm = best.get("ptm") if best.get("ptm") is not None else qmetrics.get("best_ptm")
    iptm = best.get("iptm") if best.get("iptm") is not None else qmetrics.get("best_iptm")
    plddt_mean = float(best.get("plddt_mean") or qmetrics.get("best_model_plddt") or 0.0)
    plddt_median = best.get("plddt_median")
    plddt_min = best.get("plddt_min")
    plddt_max = best.get("plddt_max")
    pae_mean = (
        best.get("pae_mean") if best.get("pae_mean") is not None else qmetrics.get("best_model_pae")
    )
    pae_min = best.get("pae_min")
    pae_max = best.get("pae_max")
    has_clash = best.get("has_clash", qmetrics.get("has_clash", 0.0))
    frac_disordered = best.get("fraction_disordered", qmetrics.get("fraction_disordered", 0.0))
    dist = best.get("plddt_distribution") or {}

    prompt = f"""You are an expert structural biologist and computational chemist reviewing AlphaFold 3 structure prediction results generated on Google Cloud Vertex AI.

**AlphaFold 3 Reference (use to interpret results):**
- Pairformer + Diffusion-based biomolecular structure prediction model supporting proteins, RNA, DNA, covalent modifications, small-molecule ligands (CCD/SMILES), and metal ions.
- **Metric interpretation thresholds:**
  - `ranking_score` (-100 to 1.5, typically 0–1): Weighted global confidence (`0.8 * ipTM + 0.2 * pTM + 0.5 * fraction_disordered - 100 * has_clash`). `>0.8` = high confidence; `>0.9` = very high confidence.
  - `pTM` (0–1): Global Template Modeling score. `>0.8` = high confidence global fold; `0.5–0.8` = moderate fold confidence; `<0.5` = uncertain global topology (common for short peptides/aptamers or Zero-MSA runs).
  - `ipTM` (0–1): Interface predicted TM-score across interacting chains/ligands. `>0.75` = reliable complex interface; `0.6–0.75` = plausible interface requiring validation; `<0.6` = uncertain binding pose/orientation.
  - `pLDDT` (0–100): Per-atom/per-residue local confidence (`>90` very high accuracy including sidechains; `70–90` confident backbone; `50–70` low confidence/flexible loop; `<50` disordered or unconstrained).
  - `PAE` (Predicted Aligned Error, Å): Expected positional error at residue `y` when aligned on residue `x`. Low off-diagonal blocks (`<5 Å`) indicate rigid inter-domain or inter-chain packing; high off-diagonal PAE (`>15 Å`) indicates independent domain motion or uncertain docking orientation.
  - `has_clash` (0 or 1) & `fraction_disordered` (0–1): Stereochemical clash penalty and fraction of residues in intrinsically disordered regions.

**Prediction Summary:**
- Target / Query Name: `{query_name}` (Job ID: `{job_id}`)
- Execution Mode: {mode_desc}
- Hardware & Turnaround: `{accel}`, Runtime `{duration_fmt}`
- Total Polymer Residues / Tokens: {total_len} across {num_chains} chain(s)
- Best Sample: `{sample_name}`

**Chain & Entity Composition:**
{chain_desc}

**Quality Metrics (Best Sample):**
- Ranking Score: `{ranking_score:.4f}`
- pTM: `{f"{ptm:.4f}" if isinstance(ptm, (int, float)) else "N/A"}`
- ipTM: `{f"{iptm:.4f}" if isinstance(iptm, (int, float)) else "N/A (monomer)"}`
- Mean pLDDT: `{plddt_mean:.2f}` (median: `{plddt_median}`, range: `[{plddt_min}, {plddt_max}]`)
- Mean PAE: `{f"{pae_mean:.2f} Å" if isinstance(pae_mean, (int, float)) else "N/A"}` (range: `[{pae_min}, {pae_max}] Å`)
- Has Clash: `{has_clash}`
- Fraction Disordered: `{frac_disordered}`

**Per-Residue Confidence Distribution (pLDDT):**
- Very High (`>=90`): {dist.get("very_high_confidence", 0)} residues
- Confident (`70–90`): {dist.get("high_confidence", 0)} residues
- Low (`50–70`): {dist.get("low_confidence", 0)} residues
- Very Low (`<50`): {dist.get("very_low_confidence", 0)} residues
"""

    if best.get("chain_ptm"):
        prompt += f"\n**Per-Chain pTM:** `{json.dumps(best['chain_ptm'])}`\n"
    if best.get("chain_iptm"):
        prompt += f"**Per-Chain ipTM:** `{json.dumps(best['chain_iptm'])}`\n"
    if best.get("chain_pair_iptm"):
        prompt += f"**Chain-Pair ipTM Matrix:** `{json.dumps(best['chain_pair_iptm'])}`\n"
    if best.get("chain_pair_pae_min"):
        prompt += f"**Chain-Pair Minimum PAE (Å):** `{json.dumps(best['chain_pair_pae_min'])}`\n"
    if seq_lines:
        prompt += (
            "\n**Input Biomolecular Entities & Sequences:**\n```\n"
            + "\n".join(seq_lines)
            + "\n```\n"
        )

    prompt += """
**Expert Analysis Request:**

Provide a comprehensive structural biology assessment covering:

1. **Overall Prediction Quality**: Evaluate the `ranking_score`, `pTM`, `ipTM`, `mean_plddt`, and `mean_pae`. How reliable is the predicted 3D structure?
2. **Per-Chain & Domain Confidence Analysis**: Analyze the per-residue pLDDT distribution and the attached pLDDT profile plot. Identify well-ordered core secondary structure elements versus flexible loops or N/C-terminal tails.
3. **Ligand / Cofactor / Nucleic Acid Coordination** (if ligands, ions, RNA, or DNA are present; otherwise evaluate active-site / binding-pocket readiness): Assess cofactor/ligand/ion placement (`ATP`, `MG`, `ZN`, inhibitor, DNA/RNA groove, etc.) using `ipTM`, `chain_pair_pae_min`, and local pLDDT.
4. **Domain Packing & Interface Analysis**: Interpret the PAE heatmap (`pae_plot`) and `chain_pair_iptm` / `chain_pair_pae_min` matrices. Which domains or inter-chain interfaces form rigid structural units, and where is conformational flexibility observed?
5. **MSA & Template Alignment Impact**: Evaluate how the execution mode (Full 630 GB MSA + PDB Templates vs. Zero-MSA `--msa-free`) influenced evolutionary co-evolutionary constraints and fold accuracy for this target.
6. **Stereochemical & Clash Assessment**: Evaluate `has_clash` and `fraction_disordered` and note any steric or topological considerations.
7. **Biological & Functional Insights**: Connect the structural features of this specific target (`query_name` / sequence) to its biological mechanism, catalytic state, or therapeutic relevance.
8. **Limitations & Recommended Next Steps**: Concrete follow-up recommendations (e.g., multi-seed ensemble sampling, holo/apo comparison, MD relaxation, FEP, or experimental cryo-EM/X-ray/SPR validation).

IMPORTANT: Begin your response directly with the markdown headings/analysis. Do NOT include conversational preamble."""
    return prompt


def generate_af3_gemini_expert_analysis(
    summary_data: dict[str, Any],
    *,
    plddt_png: bytes | None = None,
    pae_png: bytes | None = None,
    fallback_markdown: str = "",
    project_id: str | None = None,
) -> dict[str, Any]:
    """Generate multimodal Gemini Expert Analysis for AlphaFold 3 predictions."""
    now_iso = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    try:
        from google import genai
        from google.genai import types

        prompt = build_af3_expert_prompt(summary_data)
        content_parts: list[Any] = [prompt]
        if plddt_png:
            content_parts.append("\n\n**Per-Residue pLDDT Plot:**")
            content_parts.append(types.Part.from_bytes(data=plddt_png, mime_type="image/png"))
        if pae_png:
            content_parts.append("\n\n**Predicted Aligned Error (PAE) Matrix:**")
            content_parts.append(types.Part.from_bytes(data=pae_png, mime_type="image/png"))

        eff_project = project_id or os.getenv("GOOGLE_CLOUD_PROJECT") or os.getenv("GCP_PROJECT")
        if eff_project and not os.getenv("PYTEST_CURRENT_TEST"):
            preferred_model = os.getenv("GEMINI_MODEL", "gemini-3.1-pro-preview")
            candidate_models = [preferred_model] + [
                m for m in AF3_GEMINI_MODELS if m != preferred_model
            ]
            client = genai.Client(vertexai=True, project=eff_project, location="global")
            for model_name in candidate_models:
                try:
                    resp = client.models.generate_content(
                        model=model_name,
                        contents=content_parts,
                        config=types.GenerateContentConfig(temperature=0.7),
                    )
                    if resp and getattr(resp, "text", None):
                        return {
                            "status": "success",
                            "model": model_name,
                            "generated_at": now_iso,
                            "ai_generated": True,
                            "analysis": resp.text.strip() + AF3_AI_DISCLAIMER,
                        }
                except Exception as model_exc:
                    logger.warning(
                        f"AF3 Gemini expert analysis model {model_name} warning: {model_exc}"
                    )
    except Exception as exc:
        logger.warning(f"AF3 Gemini expert analysis fallback triggered: {exc}")

    return {
        "status": "success",
        "model": "gemini-3.1-pro-preview",
        "generated_at": now_iso,
        "ai_generated": True,
        "analysis": (fallback_markdown or "### AlphaFold 3 Structural Quality Assessment")
        + AF3_AI_DISCLAIMER,
    }


def compute_residue_plddts_from_cif(
    cif_text: str,
    atom_plddts: list[float] | None = None,
) -> list[float]:
    """Compute per-residue pLDDT scores from an mmCIF structure and optional per-atom pLDDT array.

    If `atom_plddts` is absent or empty, attempts to extract B-factor (pLDDT) column
    values directly from `ATOM` / `HETATM` records in the mmCIF text.
    """
    atom_lines: list[tuple[str, str, float | None]] = []
    for line in (cif_text or "").splitlines():
        if line.startswith(("ATOM ", "HETATM ")):
            parts = line.split()
            if len(parts) >= 15:
                chain_id = parts[6]
                res_seq = parts[8]
                try:
                    bfac = float(parts[14])
                except (ValueError, IndexError):
                    bfac = None
                atom_lines.append((chain_id, res_seq, bfac))

    if not atom_lines:
        if atom_plddts:
            return [float(x) for x in atom_plddts]
        return []

    res_scores: dict[tuple[str, str], list[float]] = {}
    res_order: list[tuple[str, str]] = []
    use_atom_list = bool(atom_plddts) and len(atom_plddts) == len(atom_lines)

    for idx, (chain_id, res_seq, bfac) in enumerate(atom_lines):
        score = float(atom_plddts[idx]) if use_atom_list else bfac
        if score is None:
            continue
        key = (chain_id, res_seq)
        if key not in res_scores:
            res_scores[key] = []
            res_order.append(key)
        res_scores[key].append(score)

    if not res_order and atom_plddts:
        return [float(x) for x in atom_plddts]

    return [float(np.mean(res_scores[k])) for k in res_order]


def generate_af3_plots_bytes(
    res_plddts: list[float],
    pae_matrix: list[list[float]] | None,
    title_suffix: str,
) -> tuple[bytes | None, bytes | None]:
    """Render pLDDT line plot and PAE heatmap to PNG bytes."""
    plddt_png: bytes | None = None
    pae_png: bytes | None = None

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        if res_plddts:
            fig, ax = plt.subplots(figsize=(8, 3.6), dpi=140)
            xs = np.arange(1, len(res_plddts) + 1)
            ax.axhspan(90, 100, color="#0053D6", alpha=0.12, label="Very High (>90)")
            ax.axhspan(70, 90, color="#65CBF3", alpha=0.14, label="Confident (70-90)")
            ax.axhspan(50, 70, color="#FFDB13", alpha=0.14, label="Low (50-70)")
            ax.axhspan(0, 50, color="#FF7D45", alpha=0.12, label="Very Low (<50)")
            ax.plot(xs, res_plddts, color="#0053D6", linewidth=2.0)
            ax.set_xlim(1, max(len(res_plddts), 2))
            ax.set_ylim(0, 100)
            ax.set_xlabel("Residue / Token Position")
            ax.set_ylabel("pLDDT")
            ax.set_title(
                f"AlphaFold 3 Per-Residue Confidence (pLDDT) — {title_suffix}",
                fontsize=10,
                fontweight="bold",
            )
            ax.legend(loc="lower right", fontsize=8, framealpha=0.9)
            ax.grid(True, linestyle="--", alpha=0.3)
            fig.tight_layout()
            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            plt.close(fig)
            plddt_png = buf.getvalue()

        if pae_matrix and len(pae_matrix) > 0:
            fig2, ax2 = plt.subplots(figsize=(5.2, 4.6), dpi=140)
            pae_arr = np.array(pae_matrix, dtype=float)
            im = ax2.imshow(pae_arr, cmap="Greens_r", vmin=0, vmax=31.75, origin="upper")
            cbar = fig2.colorbar(im, ax=ax2, fraction=0.046, pad=0.04)
            cbar.set_label("Expected Position Error (Å)")
            ax2.set_xlabel("Scored Residue")
            ax2.set_ylabel("Aligned Residue")
            ax2.set_title(
                f"Predicted Aligned Error (PAE) — {title_suffix}",
                fontsize=10,
                fontweight="bold",
            )
            fig2.tight_layout()
            buf2 = io.BytesIO()
            fig2.savefig(buf2, format="png")
            plt.close(fig2)
            pae_png = buf2.getvalue()
    except Exception as exc:
        logger.warning(f"Failed to render AF3 diagnostic plots: {exc}")

    return plddt_png, pae_png


def build_and_upload_af3_viewer_artifacts(
    *,
    bucket: Any,
    bucket_name: str,
    job_prefix: str,
    job_name: str,
    af3_query: dict[str, Any],
    cif_text: str,
    cif_uri: str,
    summary_confidences: dict[str, Any],
    atom_plddts: list[float] | None,
    pae_matrix: list[list[float]] | None,
    msa_free: bool,
    ranking_score: float | None,
    elapsed_sec: float | None = None,
) -> dict[str, Any]:
    """Generate and upload FoldRun Viewer summary.json and plots to GCS.

    Returns:
        Updated metrics dictionary including mean_plddt and mean_pae.
    """
    res_plddts = compute_residue_plddts_from_cif(cif_text, atom_plddts)
    if res_plddts:
        plddt_arr = np.array(res_plddts, dtype=float)
        plddt_mean = round(float(np.mean(plddt_arr)), 2)
        plddt_median = round(float(np.median(plddt_arr)), 2)
        plddt_min = round(float(np.min(plddt_arr)), 2)
        plddt_max = round(float(np.max(plddt_arr)), 2)
        plddt_dist = {
            "very_low_confidence": int(np.sum(plddt_arr < 50)),
            "low_confidence": int(np.sum((plddt_arr >= 50) & (plddt_arr < 70))),
            "high_confidence": int(np.sum((plddt_arr >= 70) & (plddt_arr < 90))),
            "very_high_confidence": int(np.sum(plddt_arr >= 90)),
        }
    else:
        raw_mean = summary_confidences.get("mean_plddt")
        plddt_mean = round(float(raw_mean), 2) if raw_mean is not None else 0.0
        plddt_median = plddt_mean
        plddt_min = plddt_mean
        plddt_max = plddt_mean
        plddt_dist = {
            "very_low_confidence": 0,
            "low_confidence": 0,
            "high_confidence": 0,
            "very_high_confidence": 0,
        }

    if pae_matrix and len(pae_matrix) > 0:
        pae_arr = np.array(pae_matrix, dtype=float)
        pae_mean = round(float(np.mean(pae_arr)), 2)
        pae_median = round(float(np.median(pae_arr)), 2)
        pae_min = round(float(np.min(pae_arr)), 2)
        pae_max = round(float(np.max(pae_arr)), 2)
    else:
        pae_mean = summary_confidences.get("mean_pae")
        pae_median = pae_mean
        pae_min = pae_mean
        pae_max = pae_mean

    mode_label = "Zero-MSA (--msa-free)" if msa_free else "Full MSA + Templates"
    plddt_png, pae_png = generate_af3_plots_bytes(
        res_plddts=res_plddts,
        pae_matrix=pae_matrix,
        title_suffix=f"{job_name} ({mode_label})",
    )

    plots_dict: dict[str, str] = {}
    if plddt_png:
        plddt_blob_path = f"{job_prefix}/analysis/plddt_plot_0.png"
        bucket.blob(plddt_blob_path).upload_from_string(plddt_png, content_type="image/png")
        plots_dict["plddt_plot"] = f"gs://{bucket_name}/{plddt_blob_path}"
    if pae_png:
        pae_blob_path = f"{job_prefix}/analysis/pae_plot_0.png"
        bucket.blob(pae_blob_path).upload_from_string(pae_png, content_type="image/png")
        plots_dict["pae_plot"] = f"gs://{bucket_name}/{pae_blob_path}"

    ptm = summary_confidences.get("ptm")
    iptm = summary_confidences.get("iptm")
    has_clash = float(summary_confidences.get("has_clash", 0.0) or 0.0)
    fraction_disordered = float(summary_confidences.get("fraction_disordered", 0.0) or 0.0)
    eff_rank_score = (
        round(float(ranking_score), 4)
        if ranking_score is not None
        else (round(float(ptm), 4) if ptm is not None else 0.0)
    )

    if plddt_mean >= 90:
        quality_assessment = "very_high_confidence"
    elif plddt_mean >= 70:
        quality_assessment = "high_confidence"
    elif plddt_mean >= 50:
        quality_assessment = "low_confidence"
    else:
        quality_assessment = "very_low_confidence"

    chain_composition = []
    total_residues = 0
    for entity in af3_query.get("sequences", []):
        for mol_type in ("protein", "rna", "dna"):
            if mol_type in entity:
                c_data = entity[mol_type]
                seq_str = c_data.get("sequence", "")
                total_residues += len(seq_str)
                chain_composition.append(
                    {
                        "chain_id": c_data.get("id", "A"),
                        "molecule_type": mol_type,
                        "residue_count": len(seq_str),
                    }
                )
        if "ligand" in entity:
            l_data = entity["ligand"]
            comp_ids = l_data.get("ccdCodes") or (
                [l_data["smiles"]] if l_data.get("smiles") else ["LIG"]
            )
            chain_composition.append(
                {
                    "chain_id": l_data.get("id", "L"),
                    "molecule_type": "ligand",
                    "comp_ids": comp_ids,
                }
            )
        if "ion" in entity:
            i_data = entity["ion"]
            chain_composition.append(
                {
                    "chain_id": i_data.get("id", "I"),
                    "molecule_type": "ligand",
                    "comp_ids": [i_data.get("ion", "ION")],
                }
            )

    now_iso = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    duration_str = f"{int(elapsed_sec // 60)}m {int(elapsed_sec % 60)}s" if elapsed_sec else "N/A"

    pred_entry = {
        k: v
        for k, v in {
            "rank": 1,
            "sample_name": "af3_seed1_sample0" if not msa_free else "af3_msa_free_sample0",
            "model_name": "AlphaFold 3",
            "cif_uri": cif_uri,
            "uri": cif_uri,
            "ranking_score": eff_rank_score,
            "ranking_confidence": eff_rank_score,
            "ptm": round(float(ptm), 4) if ptm is not None else None,
            "iptm": round(float(iptm), 4) if iptm is not None else None,
            "has_clash": has_clash,
            "fraction_disordered": fraction_disordered,
            "quality_assessment": quality_assessment,
            "plddt_mean": plddt_mean,
            "plddt_median": plddt_median,
            "plddt_min": plddt_min,
            "plddt_max": plddt_max,
            "plddt_distribution": plddt_dist,
            "pae_mean": pae_mean,
            "pae_median": pae_median,
            "pae_min": pae_min,
            "pae_max": pae_max,
            "chain_ptm": summary_confidences.get("chain_ptm"),
            "chain_iptm": summary_confidences.get("chain_iptm"),
            "chain_pair_iptm": summary_confidences.get("chain_pair_iptm"),
            "chain_pair_pae_min": summary_confidences.get("chain_pair_pae_min"),
            "plots": plots_dict,
        }.items()
        if v is not None
    }

    expert_md = (
        f"### AlphaFold 3 Structural Quality Assessment — `{job_name}`\n\n"
        f"- **Execution Mode**: {mode_label}\n"
        f"- **Turnaround Time**: `{duration_str}`\n"
        f"- **Global Confidence**: Ranking Score = `{eff_rank_score}`, "
        f"pTM = `{ptm if ptm is not None else 'N/A'}`, "
        f"Mean pLDDT = `{plddt_mean}`, "
        f"Mean PAE = `{pae_mean if pae_mean is not None else 'N/A'} Å`\n"
        f"- **Stereochemical Quality**: Clash indicator = `{has_clash}`, "
        f"Fraction disordered = `{fraction_disordered}`\n"
    )

    quality_metrics = {
        k: v
        for k, v in {
            "best_model": pred_entry["sample_name"],
            "best_model_plddt": plddt_mean,
            "best_model_pae": pae_mean,
            "best_ranking_score": eff_rank_score,
            "best_ptm": round(float(ptm), 4) if ptm is not None else None,
            "best_iptm": round(float(iptm), 4) if iptm is not None else None,
            "quality_assessment": quality_assessment,
            "mean_plddt_across_models": plddt_mean,
        }.items()
        if v is not None
    }

    viewer_summary: dict[str, Any] = {
        "job_id": job_name,
        "query_name": job_name,
        "model_type": "alphafold3",
        "analyzed_at": now_iso,
        "total_predictions": 1,
        "summary": {
            "statistics": {
                "total_predictions": 1,
                "analyzed_successfully": 1,
            },
            "quality_metrics": quality_metrics,
            "protein_info": {
                "model_type": "alphafold3",
                "sequence_length": total_residues or len(res_plddts),
                "total_length": total_residues or len(res_plddts),
                "num_chains": len(chain_composition) or 1,
                "chain_composition": chain_composition,
                "input_query_json": af3_query,
                "job_metadata": {
                    "job_id": job_name,
                    "display_name": f"{job_name} ({mode_label})",
                    "state": "PIPELINE_STATE_SUCCEEDED",
                    "duration_formatted": duration_str,
                    "create_time": now_iso,
                    "labels": {
                        "mode": "msa-free" if msa_free else "full-msa-630gb",
                        "engine": "alphafold3-v3-0-4",
                    },
                },
            },
            "recommendations": [
                "Inspect per-residue pLDDT and PAE matrices before downstream docking or free-energy perturbation.",
                "Compare --msa-free rapid screening vs. Full-MSA template-guided refinement for flexible loop regions.",
            ],
        },
        "best_prediction": pred_entry,
        "top_predictions": [pred_entry],
        "all_predictions_summary": [pred_entry],
    }

    viewer_summary["expert_analysis"] = generate_af3_gemini_expert_analysis(
        viewer_summary,
        plddt_png=plddt_png,
        pae_png=pae_png,
        fallback_markdown=expert_md,
    )

    summary_blob = bucket.blob(f"{job_prefix}/analysis/summary.json")
    summary_blob.upload_from_string(
        json.dumps(viewer_summary, indent=2), content_type="application/json"
    )

    return {
        "mean_plddt": plddt_mean,
        "mean_pae": pae_mean,
        "summary_uri": f"gs://{bucket_name}/{job_prefix}/analysis/summary.json",
    }
